version: '3'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server
    environment:
      SA_PASSWORD: "Admin123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=secret
      - SQLSERVER_HOST=sqlserver
      - SQLSERVER_PORT=1433
      - SQLSERVER_USER=sa
      - SQLSERVER_PASSWORD=Admin123
    depends_on:
      - sqlserver
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REACT_APP_API_URL=http://localhost:3000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  sqlserver_data: